"""phase 4: diagnoses, treatments, treatment plans, budgets

Revision ID: 1d6442f63a07
Revises: 440af4fb7ba6
Create Date: 2026-09-17 15:37:02.327550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d6442f63a07'
down_revision: Union[str, None] = '440af4fb7ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatments_clinic_id'), 'treatments', ['clinic_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_clinic_id'), 'treatment_plans', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_table('budgets',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_clinic_id'), 'budgets', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_budgets_patient_id'), 'budgets', ['patient_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fdi_number', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_clinic_id'), 'diagnoses', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_table('treatment_plan_items',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('fdi_number', sa.String(length=3), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plan_items_clinic_id'), 'treatment_plan_items', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_treatment_plan_items_plan_id'), 'treatment_plan_items', ['plan_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_budget_id'), 'budget_items', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_items_clinic_id'), 'budget_items', ['clinic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_items_clinic_id'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_budget_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_treatment_plan_items_plan_id'), table_name='treatment_plan_items')
    op.drop_index(op.f('ix_treatment_plan_items_clinic_id'), table_name='treatment_plan_items')
    op.drop_table('treatment_plan_items')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_clinic_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_budgets_patient_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_clinic_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_clinic_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_treatments_clinic_id'), table_name='treatments')
    op.drop_table('treatments')
    # ### end Alembic commands ###
