"""phase 12 login lockout

Revision ID: 1e407d22ac5e
Revises: ed9b8529b290
Create Date: 2026-09-20 17:05:15.251125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e407d22ac5e'
down_revision: Union[str, None] = 'ed9b8529b290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    # ### end Alembic commands ###
