"""privacy consents and staff confidentiality

Revision ID: 384e0c15c307
Revises: 87a4b5a9e245
Create Date: 2026-09-23 10:31:43.428586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '384e0c15c307'
down_revision: Union[str, None] = '87a4b5a9e245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_consents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('signed_by_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_consents_clinic_id'), 'data_consents', ['clinic_id'], unique=False)
    op.create_index('ix_data_consents_patient_kind', 'data_consents', ['patient_id', 'kind', sa.text('recorded_at DESC')], unique=False)
    op.add_column('users', sa.Column('confidentiality_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('confidentiality_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confidentiality_version')
    op.drop_column('users', 'confidentiality_accepted_at')
    op.drop_index('ix_data_consents_patient_kind', table_name='data_consents')
    op.drop_index(op.f('ix_data_consents_clinic_id'), table_name='data_consents')
    op.drop_table('data_consents')
    # ### end Alembic commands ###
