"""password must change

Revision ID: 3a6ae1725126
Revises: afc07d623ef5
Create Date: 2026-10-02 10:54:38.855624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a6ae1725126'
down_revision: Union[str, None] = 'afc07d623ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
