"""phase 3: odontogram snapshots and tooth conditions

Revision ID: 440af4fb7ba6
Revises: 443a08e37f77
Create Date: 2026-09-17 12:12:08.080927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '440af4fb7ba6'
down_revision: Union[str, None] = '443a08e37f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odontograms',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_odontogram_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['previous_odontogram_id'], ['odontograms.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odontograms_clinic_id'), 'odontograms', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_odontograms_patient_id'), 'odontograms', ['patient_id'], unique=False)
    op.create_table('tooth_conditions',
    sa.Column('odontogram_id', sa.UUID(), nullable=False),
    sa.Column('fdi_number', sa.String(length=3), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['odontogram_id'], ['odontograms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tooth_conditions_clinic_id'), 'tooth_conditions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tooth_conditions_odontogram_id'), 'tooth_conditions', ['odontogram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tooth_conditions_odontogram_id'), table_name='tooth_conditions')
    op.drop_index(op.f('ix_tooth_conditions_clinic_id'), table_name='tooth_conditions')
    op.drop_table('tooth_conditions')
    op.drop_index(op.f('ix_odontograms_patient_id'), table_name='odontograms')
    op.drop_index(op.f('ix_odontograms_clinic_id'), table_name='odontograms')
    op.drop_table('odontograms')
    # ### end Alembic commands ###
