"""phase 2: patients and versioned medical history

Revision ID: 443a08e37f77
Revises: 2cb0d1435297
Create Date: 2026-09-17 12:03:16.884077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '443a08e37f77'
down_revision: Union[str, None] = '2cb0d1435297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patients_national_id'), 'patients', ['national_id'], unique=False)
    op.create_table('medical_histories',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('surgeries', sa.Text(), nullable=True),
    sa.Column('habits', sa.Text(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=True),
    sa.Column('vital_signs', sa.Text(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('present_illness_history', sa.Text(), nullable=True),
    sa.Column('oral_hygiene', sa.Text(), nullable=True),
    sa.Column('dental_habits', sa.Text(), nullable=True),
    sa.Column('dental_history', sa.Text(), nullable=True),
    sa.Column('extraoral_exam', sa.Text(), nullable=True),
    sa.Column('intraoral_exam', sa.Text(), nullable=True),
    sa.Column('soft_tissues', sa.Text(), nullable=True),
    sa.Column('gums', sa.Text(), nullable=True),
    sa.Column('periodontium', sa.Text(), nullable=True),
    sa.Column('tmj', sa.Text(), nullable=True),
    sa.Column('occlusion', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_histories_clinic_id'), 'medical_histories', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_medical_histories_patient_id'), 'medical_histories', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_histories_patient_id'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_clinic_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_patients_national_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
