"""phase 5: appointments and reminders

Revision ID: 5920ec9072fa
Revises: 1d6442f63a07
Create Date: 2026-09-18 14:43:38.000162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5920ec9072fa'
down_revision: Union[str, None] = '1d6442f63a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('operatory_id', sa.UUID(), nullable=True),
    sa.Column('treatment_id', sa.UUID(), nullable=True),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('color_hex', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operatory_id'], ['operatories.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_table('appointment_reminders',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_reminders_appointment_id'), 'appointment_reminders', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_clinic_id'), 'appointment_reminders', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_scheduled_for'), 'appointment_reminders', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###

    # Double-booking is prevented by the database itself, not only by the
    # service layer: two receptionists saving the same slot at the same instant
    # must not both succeed. btree_gist lets a GiST exclusion constraint mix the
    # equality check on the professional/operatory with the range overlap check.
    # Cancelled and no-show appointments free their slot, hence the WHERE clause.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE appointments
        ADD CONSTRAINT appointments_no_professional_overlap
        EXCLUDE USING gist (
            professional_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        )
        WHERE (status NOT IN ('cancelada', 'no_asistio'))
        """
    )
    op.execute(
        """
        ALTER TABLE appointments
        ADD CONSTRAINT appointments_no_operatory_overlap
        EXCLUDE USING gist (
            operatory_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        )
        WHERE (operatory_id IS NOT NULL AND status NOT IN ('cancelada', 'no_asistio'))
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_no_operatory_overlap")
    op.execute("ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_no_professional_overlap")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_reminders_scheduled_for'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_clinic_id'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_appointment_id'), table_name='appointment_reminders')
    op.drop_table('appointment_reminders')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
