"""refresh token rotation grace

Revision ID: 77b64eb2ae4d
Revises: eb86d84b1c1a
Create Date: 2026-09-28 10:00:40.014031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77b64eb2ae4d'
down_revision: Union[str, None] = 'eb86d84b1c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'rotated_at')
    # ### end Alembic commands ###
