"""void diagnoses and prescriptions

Revision ID: 87a4b5a9e245
Revises: 1e407d22ac5e
Create Date: 2026-09-21 16:18:15.900154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87a4b5a9e245'
down_revision: Union[str, None] = '1e407d22ac5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('diagnoses', sa.Column('void_reason', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('voided_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_diagnoses_voided_by', 'diagnoses', 'users', ['voided_by_id'], ['id'])
    op.add_column('prescriptions', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prescriptions', sa.Column('void_reason', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('voided_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_prescriptions_voided_by', 'prescriptions', 'users', ['voided_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_prescriptions_voided_by', 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'voided_by_id')
    op.drop_column('prescriptions', 'void_reason')
    op.drop_column('prescriptions', 'voided_at')
    op.drop_constraint('fk_diagnoses_voided_by', 'diagnoses', type_='foreignkey')
    op.drop_column('diagnoses', 'voided_by_id')
    op.drop_column('diagnoses', 'void_reason')
    op.drop_column('diagnoses', 'voided_at')
    # ### end Alembic commands ###
