"""phase 11 messaging ai suggestions and patient portal

Revision ID: a729cda1b80d
Revises: 52047037d6e6
Create Date: 2026-09-20 16:48:54.039560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a729cda1b80d'
down_revision: Union[str, None] = '52047037d6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'code', name='uq_template_code')
    )
    op.create_index(op.f('ix_message_templates_clinic_id'), 'message_templates', ['clinic_id'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('context_used', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_clinic_id'), 'ai_suggestions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_patient_id'), 'ai_suggestions', ['patient_id'], unique=False)
    op.create_table('portal_accesses',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_accesses_clinic_id'), 'portal_accesses', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_portal_accesses_patient_id'), 'portal_accesses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_portal_accesses_token_hash'), 'portal_accesses', ['token_hash'], unique=True)
    op.create_table('outbound_messages',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('to_address', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_message_id', sa.String(length=160), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['appointment_reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_appointment_id'), 'outbound_messages', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_clinic_id'), 'outbound_messages', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_patient_id'), 'outbound_messages', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_patient_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_clinic_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_appointment_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_portal_accesses_token_hash'), table_name='portal_accesses')
    op.drop_index(op.f('ix_portal_accesses_patient_id'), table_name='portal_accesses')
    op.drop_index(op.f('ix_portal_accesses_clinic_id'), table_name='portal_accesses')
    op.drop_table('portal_accesses')
    op.drop_index(op.f('ix_ai_suggestions_patient_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_clinic_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_message_templates_clinic_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
