"""credits

Revision ID: afc07d623ef5
Revises: 77b64eb2ae4d
Create Date: 2026-09-28 10:05:35.992012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'afc07d623ef5'
down_revision: Union[str, None] = '77b64eb2ae4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.UUID(), nullable=False),
    sa.Column('interest_charge_id', sa.UUID(), nullable=True),
    sa.Column('down_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('first_due_on', sa.Date(), nullable=False),
    sa.Column('guarantor_name', sa.String(length=200), nullable=True),
    sa.Column('guarantor_id_number', sa.String(length=30), nullable=True),
    sa.Column('guarantor_phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('monthly_rate >= 0', name='ck_credit_rate_non_negative'),
    sa.CheckConstraint('principal > 0', name='ck_credit_principal_positive'),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interest_charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_charge_id'), 'credits', ['charge_id'], unique=False)
    op.create_index(op.f('ix_credits_clinic_id'), 'credits', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_credits_patient_id'), 'credits', ['patient_id'], unique=False)
    op.create_table('credit_installments',
    sa.Column('credit_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_credit_installment_positive'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_installments_clinic_id'), 'credit_installments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_credit_installments_credit_id'), 'credit_installments', ['credit_id'], unique=False)
    op.add_column('payments', sa.Column('credit_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('split_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_credit_id'), 'payments', ['credit_id'], unique=False)
    op.create_foreign_key('fk_payments_credit', 'payments', 'credits', ['credit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payments_credit', 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_credit_id'), table_name='payments')
    op.drop_column('payments', 'split_group_id')
    op.drop_column('payments', 'credit_id')
    op.drop_index(op.f('ix_credit_installments_credit_id'), table_name='credit_installments')
    op.drop_index(op.f('ix_credit_installments_clinic_id'), table_name='credit_installments')
    op.drop_table('credit_installments')
    op.drop_index(op.f('ix_credits_patient_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_clinic_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_charge_id'), table_name='credits')
    op.drop_table('credits')
    # ### end Alembic commands ###
