"""archive documents and void consents

Revision ID: b37fbbca9f24
Revises: 384e0c15c307
Create Date: 2026-09-23 18:23:05.416859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b37fbbca9f24'
down_revision: Union[str, None] = '384e0c15c307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consents', sa.Column('void_reason', sa.Text(), nullable=True))
    op.add_column('consents', sa.Column('voided_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_consents_voided_by', 'consents', 'users', ['voided_by_id'], ['id'])
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('archived_by_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('archived_reason', sa.Text(), nullable=True))
    op.create_foreign_key('fk_documents_archived_by', 'documents', 'users', ['archived_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_archived_by', 'documents', type_='foreignkey')
    op.drop_column('documents', 'archived_reason')
    op.drop_column('documents', 'archived_by_id')
    op.drop_column('documents', 'archived_at')
    op.drop_constraint('fk_consents_voided_by', 'consents', type_='foreignkey')
    op.drop_column('consents', 'voided_by_id')
    op.drop_column('consents', 'void_reason')
    op.drop_column('consents', 'voided_at')
    # ### end Alembic commands ###
