"""phase 7 periodontogram and clinical imaging

Revision ID: e0aac5aa10d2
Revises: 6f516cea17c5
Create Date: 2026-09-18 21:09:13.400371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0aac5aa10d2'
down_revision: Union[str, None] = '6f516cea17c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_images',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taken_on', sa.Date(), nullable=True),
    sa.Column('fdi_numbers', sa.ARRAY(sa.String(length=3)), nullable=True),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_images_clinic_id'), 'clinical_images', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinical_images_patient_id'), 'clinical_images', ['patient_id'], unique=False)
    op.create_table('periodontograms',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_periodontogram_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['previous_periodontogram_id'], ['periodontograms.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodontograms_clinic_id'), 'periodontograms', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_periodontograms_patient_id'), 'periodontograms', ['patient_id'], unique=False)
    op.create_table('periodontal_measurements',
    sa.Column('periodontogram_id', sa.UUID(), nullable=False),
    sa.Column('fdi_number', sa.String(length=3), nullable=False),
    sa.Column('site', sa.String(length=24), nullable=False),
    sa.Column('probing_depth', sa.Integer(), nullable=True),
    sa.Column('recession', sa.Integer(), nullable=True),
    sa.Column('bleeding', sa.Boolean(), nullable=False),
    sa.Column('suppuration', sa.Boolean(), nullable=False),
    sa.Column('plaque', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['periodontogram_id'], ['periodontograms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodontal_measurements_clinic_id'), 'periodontal_measurements', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_periodontal_measurements_periodontogram_id'), 'periodontal_measurements', ['periodontogram_id'], unique=False)
    op.create_table('periodontal_teeth',
    sa.Column('periodontogram_id', sa.UUID(), nullable=False),
    sa.Column('fdi_number', sa.String(length=3), nullable=False),
    sa.Column('absent', sa.Boolean(), nullable=False),
    sa.Column('implant', sa.Boolean(), nullable=False),
    sa.Column('mobility', sa.SmallInteger(), nullable=True),
    sa.Column('furcation', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['periodontogram_id'], ['periodontograms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodontal_teeth_clinic_id'), 'periodontal_teeth', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_periodontal_teeth_periodontogram_id'), 'periodontal_teeth', ['periodontogram_id'], unique=False)

    # The service rejects duplicate probe readings, but the guarantee belongs
    # in the database: an index computed over a doubled site is silently wrong,
    # and nothing downstream would flag it.
    op.create_unique_constraint(
        "uq_periodontal_measurement_site",
        "periodontal_measurements",
        ["periodontogram_id", "fdi_number", "site"],
    )
    op.create_unique_constraint(
        "uq_periodontal_tooth",
        "periodontal_teeth",
        ["periodontogram_id", "fdi_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_periodontal_tooth", "periodontal_teeth", type_="unique")
    op.drop_constraint("uq_periodontal_measurement_site", "periodontal_measurements", type_="unique")
    op.drop_index(op.f('ix_periodontal_teeth_periodontogram_id'), table_name='periodontal_teeth')
    op.drop_index(op.f('ix_periodontal_teeth_clinic_id'), table_name='periodontal_teeth')
    op.drop_table('periodontal_teeth')
    op.drop_index(op.f('ix_periodontal_measurements_periodontogram_id'), table_name='periodontal_measurements')
    op.drop_index(op.f('ix_periodontal_measurements_clinic_id'), table_name='periodontal_measurements')
    op.drop_table('periodontal_measurements')
    op.drop_index(op.f('ix_periodontograms_patient_id'), table_name='periodontograms')
    op.drop_index(op.f('ix_periodontograms_clinic_id'), table_name='periodontograms')
    op.drop_table('periodontograms')
    op.drop_index(op.f('ix_clinical_images_patient_id'), table_name='clinical_images')
    op.drop_index(op.f('ix_clinical_images_clinic_id'), table_name='clinical_images')
    op.drop_table('clinical_images')
    # ### end Alembic commands ###
