"""expenses

Revision ID: eb86d84b1c1a
Revises: b37fbbca9f24
Create Date: 2026-09-28 09:48:29.697922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb86d84b1c1a'
down_revision: Union[str, None] = 'b37fbbca9f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('supplier_name', sa.String(length=160), nullable=True),
    sa.Column('receipt_number', sa.String(length=80), nullable=True),
    sa.Column('cash_session_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_clinic_id'), 'expenses', ['clinic_id'], unique=False)
    op.create_index('ix_expenses_clinic_spent', 'expenses', ['clinic_id', 'spent_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_clinic_spent', table_name='expenses')
    op.drop_index(op.f('ix_expenses_clinic_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
