"""phase 8 charges payments installments and cash sessions

Revision ID: f8fbc6011a77
Revises: e0aac5aa10d2
Create Date: 2026-09-20 12:25:42.906858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8fbc6011a77'
down_revision: Union[str, None] = 'e0aac5aa10d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_by_id', sa.UUID(), nullable=True),
    sa.Column('opening_float', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('counted_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_clinic_id'), 'cash_sessions', ['clinic_id'], unique=False)
    op.create_table('charges',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_charge_amount_positive'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', name='uq_charge_budget')
    )
    op.create_index(op.f('ix_charges_clinic_id'), 'charges', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_charges_patient_id'), 'charges', ['patient_id'], unique=False)
    op.create_table('installments',
    sa.Column('charge_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_installment_amount_positive'),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge_id', 'number', name='uq_installment_number')
    )
    op.create_index(op.f('ix_installments_charge_id'), 'installments', ['charge_id'], unique=False)
    op.create_index(op.f('ix_installments_clinic_id'), 'installments', ['clinic_id'], unique=False)
    op.create_table('payments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.UUID(), nullable=True),
    sa.Column('cash_session_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_cash_session_id'), 'payments', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_payments_charge_id'), 'payments', ['charge_id'], unique=False)
    op.create_index(op.f('ix_payments_clinic_id'), 'payments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_clinic_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_cash_session_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_installments_clinic_id'), table_name='installments')
    op.drop_index(op.f('ix_installments_charge_id'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_charges_patient_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_clinic_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_cash_sessions_clinic_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
