"""File storage behind one interface.

Clinical files (documents now, radiographs in the next phase) are never written
through a provider-specific API by the business code: everything goes through
`StorageProvider`. Swapping local disk for S3 is then a config change, not a
rewrite — which is the whole reason this abstraction exists from the start.
"""

import uuid
from abc import ABC, abstractmethod
from pathlib import Path

from app.core.config import get_settings


class StorageProvider(ABC):
    @abstractmethod
    async def save(self, clinic_id: uuid.UUID, filename: str, content: bytes) -> str:
        """Stores the bytes and returns the key needed to read them back."""

    @abstractmethod
    async def read(self, key: str) -> bytes: ...

    @abstractmethod
    async def delete(self, key: str) -> None: ...


class LocalStorageProvider(StorageProvider):
    """Development / single-clinic deployments: files live on the server's disk,
    partitioned per clinic so one clinic's data never sits in another's folder."""

    def __init__(self, base_path: str):
        self.base_path = Path(base_path)

    def _resolve(self, key: str) -> Path:
        path = (self.base_path / key).resolve()
        # A key is generated by us, but resolving guards against a traversal
        # ("../../etc/passwd") ever reaching the filesystem.
        if not str(path).startswith(str(self.base_path.resolve())):
            raise ValueError("Ruta de archivo inválida")
        return path

    async def save(self, clinic_id: uuid.UUID, filename: str, content: bytes) -> str:
        suffix = Path(filename).suffix[:12]
        key = f"{clinic_id}/{uuid.uuid4().hex}{suffix}"
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return key

    async def read(self, key: str) -> bytes:
        return self._resolve(key).read_bytes()

    async def delete(self, key: str) -> None:
        self._resolve(key).unlink(missing_ok=True)


def get_storage() -> StorageProvider:
    settings = get_settings()
    if settings.STORAGE_PROVIDER == "s3":
        # Deliberately not implemented yet rather than faked: the S3 client and
        # its credentials belong to the deployment phase. Everything that calls
        # this already speaks the interface, so only this branch changes.
        raise NotImplementedError(
            "El proveedor S3 aún no está implementado. Use STORAGE_PROVIDER=local."
        )
    return LocalStorageProvider(settings.STORAGE_LOCAL_PATH)
